version: "3"

name: peratorakka_server
services:
  http_server:
    build:
      context: "."
      target: production
    image: peratorakka/http_server
    depends_on:
      - relational_database_server
    container_name: peratorakka_http_server
    ports:
      - ${HTTP_PORT}:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    networks:
      - peratorakka_server

  relational_database_server:
    image: postgres
    container_name: relational_database_server
    ports:
      - ${RELATIONAL_DATABASE_PORT}:5432
    restart: always
    environment:
      POSTGRES_DB: ${RELATIONAL_DATABASE_NAME}
      POSTGRES_USER: ${RELATIONAL_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${RELATIONAL_DATABASE_PASSWORD}
    networks:
      - peratorakka_server
    volumes:
      - ${RELATIONAL_DATABASE_DIRECTORY}:/var/lib/postgresql/data

networks:
  peratorakka_server:
    name: peratorakka_server-network
