name: Backend Tests

on:
  push: []
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - review_requested
    branches:
      - master
    paths:
      - 'src/**'

jobs:
  backend_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@2.28.0
      with:
        php-version: "8.1"
      env:
        COMPOSER_TOKEN: ${{ secrets.COMPOSER_TOKEN }}
    - uses: actions/checkout@v2
    - name: Copy env
      run: php -r "file_exists('.env.ci') || copy('.env.ci', '.env');"
    - name: Cache vendors
      uses: actions/cache@v3
      with:
        path: ./vendor
        key: ${{ runner.os }}_8.1_${{ hashFiles('composer.*') }}
        restore-keys: |
          ${{ runner.os }}_8.1_${{ hashFiles('composer.*') }}
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Set Writable Directory Permissions
      run: chmod -R a+rwx writable
    - name: Run all tests
      run: composer run test:offline:all
